### ISSUE TITLE
error when culled mesh

### ISSUE THREAD

**Issue by 00Haocheng** [JingwenWang95/neural_slam_eval#6]
Thank you for sharing this excellent work, but when I run the command
python cull_mesh.py --config configs/Replica/room0.yaml --input_mesh $INPUT_MESH --remove_occlusion --virtual_cameras --virt_cam_path $VIRT_CAM_PATH --gt_pose

there is an error like

Using Co-SLAM culling strategy...
Added 90 virtual views from eval_data/Replica/room0/virtual_cameras
rendering depth maps...
libEGL warning: DRI2: failed to create dri screen
libEGL warning: Not allowed to force software rendering when API explicitly selects a hardware device.
libEGL warning: DRI2: failed to create dri screen
Traceback (most recent call last):
  File "cull_mesh.py", line 317, in <module>
    virtual_cameras=args.virtual_cameras, virt_cam_path=args.virt_cam_path)
  File "cull_mesh.py", line 225, in cull_one_mesh
    rendered_depth_maps = render_depth_maps_doublesided(mesh, c2w_list, K, H, W, near=0.01, far=10.0)
  File "cull_mesh.py", line 80, in render_depth_maps_doublesided
    depth_maps_1 = render_depth_maps(mesh, poses, K, H, W, near=near, far=far)
  File "cull_mesh.py", line 67, in render_depth_maps
    renderer = pyrender.OffscreenRenderer(W, H)
  File "/home/zju231/anaconda3/envs/eslam/lib/python3.7/site-packages/pyrender/offscreen.py", line 31, in __init__
    self._create()
  File "/home/zju231/anaconda3/envs/eslam/lib/python3.7/site-packages/pyrender/offscreen.py", line 149, in _create
    self._platform.init_context()
  File "/home/zju231/anaconda3/envs/eslam/lib/python3.7/site-packages/pyrender/platforms/egl.py", line 177, in init_context
    assert eglInitialize(self._egl_display, major, minor)
  File "/home/zju231/anaconda3/envs/eslam/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 402, in __call__
    return self( *args, **named )
  File "/home/zju231/anaconda3/envs/eslam/lib/python3.7/site-packages/OpenGL/error.py", line 232, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 12289,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7fa197aff8c0>,
		c_long(0),
		c_long(0),
	),
	result = 0
)

Maybe its an error about pyrender,  how can I solve it

**Comment by hlldy6858** [comment]
Have you solved this problem? I also encountered the same problem

**Comment by 00Haocheng** [comment]
I thought it might be a problem with the version of some packages, so I created a whole new environment and configured it all the way from coslam. And it can work

**Comment by hlldy6858** [comment]
Thank you very much！Can you please mention your CUDA and pytorch versions？

**Comment by 00Haocheng** [comment]
cuda_11.3 and  torch1.10.1+cu113

**Comment by hlldy6858** [comment]
Thanks again
